### ISSUE TITLE
Possible calculation bug

### ISSUE THREAD

**Issue by WH17EW0LF** [jbowensii/More-Automated-Spells-Items-and-Feats#1]
When I roll to attack with a character that has Piercer feat, I get a popup when I click damage asking if I want to reroll the damage die. 
If I click yes it rerolls, applies the original damage to the attack then heals for the new roll?!

https://cdn.discordapp.com/attachments/965675305735970826/974295691759321148/unknown.png
https://cdn.discordapp.com/attachments/965675305735970826/974296955721248818/unknown.png
https://cdn.discordapp.com/attachments/965675305735970826/974296955964510249/unknown.png

**Comment by jbowensii** [comment]
Sorry, work interfered with me looking at his yesterday. 
So in the workflow, the roll for damage is already made, you cannot go back and change it.  
Tim suggested if the player chooses to make a new roll then change the delta.  
AKA:
EXAMPLE 1:  If the original roll was a 6 and the reroll is a 2, then heal back 4 after the original damage.
EXAMPLE 2: If the original roll was 2 and the reroll is a 6, then apply 4 damage after the original damage.

So this works as designed.  MIDI-QOL does not have a (go back in the workflow and reroll) capability.  
Not perfect but mathematically correct.

**Comment by jbowensii** [comment]
Sorry, work interfered with me looking at his yesterday. 
So in the workflow, the roll for damage is already made, you cannot go back and change it.  
Tim suggested if the player chooses to make a new roll then change the delta.  
AKA:
EXAMPLE 1:  If the original roll was a 6 and the reroll is a 2, then heal back 4 after the original damage.
EXAMPLE 2: If the original roll was 2 and the reroll is a 6, then apply 4 damage after the original damage.

So this works as designed.  MIDI-QOL does not have a (go back in the workflow and reroll) capability.  
Not perfect but mathematically correct.
