### ISSUE TITLE
Orcish Fury triggering every time

### ISSUE THREAD

**Issue by ctbritt** [jbowensii/More-Automated-Spells-Items-and-Feats#1]
Not sure if I have this set up properly, but orcish fury is presenting me with a dialog every time on my barbarian. 

I have an attribute (tertiary) set up as "Orcish Fury" with a short/long rest recharge.
When I attack, it triggers the orcish fury dialog. I click yes, use OF. Midi-QOL's cards show the orcish fury damage, but not the main damage. 
![Screen Shot 2022-04-19 at 8 56 22 PM](https://user-images.githubusercontent.com/4516034/164125707-91f80cfb-3313-4b2a-9f17-183473c14be2.png)
Then, it keeps asking me if I want to use OF, even if the attribute count is 0/1.

Here's how I have it set up: 
![Screen Shot 2022-04-19 at 8 58 12 PM](https://user-images.githubusercontent.com/4516034/164125854-2e68ca5d-87e5-462a-8770-93a625326653.png)

I also get negative uses in the attribute field if I continue to use it. 

![Screen Shot 2022-04-19 at 8 59 24 PM](https://user-images.githubusercontent.com/4516034/164125964-8be3b6e8-29c5-404e-9a66-44bb28b9f871.png)

Thoughts?

**Comment by jbowensii** [comment]
I will look into this over the weekend, thank you...

**Comment by ctbritt** [comment]
it's still not showing the base damage. It flashes for a split second, then disappears. And it's still offering to use orcish fury, even after its set to 0/1 in the resources section.

**Comment by ctbritt** [comment]
Have fixed the issue of it continuing to call orcish fury every time. (see my edit in the macro...) but have not figured out why it's not hiding the base damage... how do you have midi configured to show damage cards?

**Comment by ctbritt** [comment]
Ok. have also found out it's an issue with how midi displays the damage cards. If either `merge rolls to one card` or `condense attack/damage` rolls are checked, it will not display the base damage done.

**Comment by ctbritt** [comment]
more on this. I see you've taken @tposney's `new Midi.QOL.DamageOnlyWorkflow` from his divine smite example. But that's hiding the base damage for some reason. Working on this one.

**Comment by jbowensii** [comment]
I have re-opened this issue since it seems like you are seeing something I do not.  
I do not see a proposed change to the macro, save a copy of your macro and put the extension txt on it, and attach it to a message please.  make sure to give yourself credit at the top of the header for the fix.  I will review and integrate it.   I only use midi for the damage cards which you see as my example above.  

<img width="391" alt="image" src="https://user-images.githubusercontent.com/76136571/164791422-f8bb9062-0dcd-47e4-89bd-cbb33687520e.png">

**Comment by ctbritt** [comment]
thanks for your reply. I'm not sure what is happening... I also noticed that your macro won't work if you don't have the [hints] on the damage roll for Midi, so I added some work on that as well. My modified macro is here: 
`console.log("args: ", args)
/*****
Orcish Fury

USEAGE : AUTOMATIC
This item should be placed on the character that has the Orcish Fury Feat.  
Until used, during each melee attack the player will be prompted if they
want to use this ability.
 
MANEUVER DESCRIPTION:
When you hit with an attack using a simple or martial weapon, you can roll one 
of the weapon’s damage dice an additional time and add it as extra damage of 
the weapon’s damage type. Once you use this ability, you can’t use it again 
until you finish a short or long rest.

v0.2 April 12 2022 jbowens #0415 (Discord) https://github.com/jbowensii/More-Automated-Spells-Items-and-Feats.git 
*****/

// make sure the attempted hit was made with a weapon attack
if (!["mwak","rwak"].includes(args[0].item.data.actionType)) return;

if (args[0].macroPass === "preDamageRoll") {
	const pcActor = MidiQOL.MQfromActorUuid(args[0].actorUuid);
	const target = await fromUuid(args[0].hitTargetUuids[0] ?? "");

	// check to make sure only one target is selected
	if ((args[0].targetUuids.length < 1) || (args[0].targetUuids.length > 1)) {
		ui.notifications.error("You need to select a single target.");
		return;
	}

	// Find Superiority Dice Resource
	let orcishFury = await findSheetResource(pcActor, "Orcish Fury");
	if (!orcishFury) { 
		ui.notifications.error("Could not find a resource labeled 'Orcish Fury'...");  // fixed typo on resource
		return;
	} else if (orcishFury.value < 1) return; // here is the change needed for the value.

	// create a dialog and prompt to spend a superiority die
	let dialog = new Promise((resolve) => {
		new Dialog({
			// localize this text
			title: "Orcish Fury:",
			content: "<p>Use Orcish Fury for extra damage?</p>",
			buttons: {
				one: {
					icon: '<p> </p><img src = "systems/dnd5e/icons/skills/red_01.jpg" width="60" height="60"></>',
					label: "<p>Yes</p>",
					callback: () => resolve(true)
				},
				two: {
					icon: '<p> </p><img src = "systems/dnd5e/icons/skills/weapon_28.jpg" width="60" height="60"></>',
					label: "<p>No</p>",
					callback: () => {resolve(false)}
				}
			},
			default: "two"
		}).render(true);
	});
	let choice = await dialog;

	if (!choice) return;

	// if YES subtract a superiorty die
	await decrimentSheetResource (pcActor, "Orcish Fury", 1);

	// get the live MIDI-QOL workflow so we can make changes
	const diceMult = args[0].isCritical ? 2 : 1;
	let die = "";
	let baseDice = (1 * diceMult);
	if (args[0].item.data.damage.parts[0][0].includes('[')) { // here we check if there are hints or not
		die = args[0].item.data.damage.parts[0][0].split('[')[0]; // everything before the [
	} else {
		die = args[0].item.data.damage.parts[0][0].split('+')[0];
	}	die = die.toLowerCase();                                        // convert the string to lower case
	let baseDie = die.split('d')[1];                                //everything after the 'd' the die size and any mods << this needs work
	let furyRoll = (baseDice+"d"+baseDie);                          // assemble the FuryRoll
	const damageType = args[0].item.data.damage.parts[0][1];        // get teh damage type from the weapon in use   
	
	console.log("diceMult: ", diceMult);
	console.log("baseDice: ", baseDice);
	console.log("die: ", die);
	console.log("baseDie: ", baseDie);
	console.log("furyRoll: ", furyRoll);
	console.log("damageType: ", damageType);
	
	
	// roll the damage and add it to the workflow
	let furyDamage = await new Roll(furyRoll).roll();
	console.log("damageRoll.total: ", furyDamage.total);
	new MidiQOL.DamageOnlyWorkflow(actor, token, damageRoll.total, damageType, target ? [target] : [], damageRoll, {flavor: "Orcish Fury", itemCardId: args[0].itemCardId});
	return; 
}

//---------------------------------- MY FUNCTIONS -------------------------------------

// Test for available resource
// Return resource object
async function findSheetResource (testActor, resourceName) {
	let resources = Object.values(testActor.data.data.resources);
	let foundResource = resources.find(i => i.label.toLowerCase() === resourceName.toLowerCase());
	return foundResource;
}

// Decriment available resource
async function decrimentSheetResource (testActor, resourceName, numValue) {
	let actorDup = duplicate(testActor.data._source);
	let resources = Object.values(actorDup.data.resources);
	let foundResource = resources.find(i => i.label.toLowerCase() === resourceName.toLowerCase());
	foundResource.value = foundResource.value - numValue;
	await testActor.update(actorDup); 
	return;
}`

**Comment by ctbritt** [comment]
this is what i'm seeing on a hit. 
<img width="291" alt="Screen Shot 2022-04-22 at 5 06 36 PM" src="https://user-images.githubusercontent.com/4516034/164793554-107a8400-deb8-4c2e-a39c-97288e634fae.png">

**Comment by jbowensii** [comment]
I will definitely look at this tomorrow morning, I am running The Dungeon of the Mage mage in a couple of hours for 8 folks and have to finish prepping.  Thank you... John

**Comment by jbowensii** [comment]
Last night I ran the game that used this macro... thank you for the spelling and .value fix... :)  I added your name to the top of the macro btw, hope you do not mind. 

From the characters perspective this is what I get: 
<img width="217" alt="image" src="https://user-images.githubusercontent.com/76136571/164894202-56deae97-85a2-4c01-be65-bc20387bd8d2.png">

and from the GMs:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/76136571/164894206-18a80aaf-b3e0-47c7-b012-faf0a4a9be72.png">

Even with multiple effects like colossus slayer and oricish fury I see them all...

**Comment by jbowensii** [comment]
I am halfway done documenting my game settings online... I am interested if you see anything.  https://github.com/jbowensii/FOUNDRYVTT-DnD5e-Base-Game-Configuration

**Comment by jbowensii** [comment]
Tim Poseny helped me with a fix... thank you Tim.  

Point to note, this was a race condition, this is what Tim wrote:

I can think of 3 solutions:
1. Delay the orcish fury macro to a later time in the workflow (e.g postActiveEffects), which will pretty much ensure the chat card update will have been completed before the user can push yes on the use of Orcish fury.
2. Create a new chat card for the orcish fury damage (specify itemCardId = new and pass an item - probably orcish fury - to the new DamageWorkflow so it can create an item card).
3. Turn the Orcish Fury into a DamageBonusMacro, rather than an actorOnUseMacro, since that guarantees to play nicely with the original workflow. It's almost identical.

**DamgeBonusMacros are pretty much exactly intended for this sort of feature.**

Sneak attack, for example, is a DamageBonusMacro

**Comment by jbowensii** [comment]
closed with release 0.7.0
