### ISSUE TITLE
Thanks, need more instructions, and receiving an error.

### ISSUE THREAD

**Issue by rprejean** [jbowensii/More-Automated-Spells-Items-and-Feats#2]
First of all, thank you. This looks promising and like a lot of work. 
I am specifically trying to use it for Battle Master Maneuvers. Is there a comprehensive how-to written to get started other than the notes in the feat and effects descriptions?

------------------EDIT/UPDATE RESOLVED------------------
After two days of tinkering and a lot of help from the Foundry Community, I was able to get this working. I've written settup guide to help others interested in using this module. 

https://docs.google.com/document/d/1dk58Tme1DTaC7-sq_V-0KEKx6PvwvN03bhom2LRkIFk/edit?usp=sharing

**Comment by rprejean** [comment]
Other questions:
Need clarification, In regards to the image below, does this setting get set up on every weapon the PC will be using? Or does it get setup on the feature itself?
![image](https://user-images.githubusercontent.com/4765489/190057834-18bb252f-67c8-4f8b-a519-99517ecf5d1f.png)

For the image below, where is the damage derived from? When activate, it rolls 0/0
![image](https://user-images.githubusercontent.com/4765489/190057987-6e58c951-bfd2-49d9-877f-a0d7a97fed7a.png)

With Superiority dice as an effect, where are the remaining "charges" tracked? When I applied the first picture's Resource Consumption to either the weapon or the feat I received an error that there was no attribute to spend.

Again, thank you. Just need some direction.

**Comment by rprejean** [comment]
Doing some tinkering, I figured out the answer to a few of my questions and started this simple How To. I don't know macro editing very well, so I do not know why the die rolls are not registering.

**Setting up Battle Master Maneuvers**
[More-Automated-Spells-Items-and-Feats]
From <https://github.com/jbowensii/More-Automated-Spells-Items-and-Feats> 
--- This assumes you have installed MASIF and all required mods. For instructions go to Jbowenssii's Github above.

	1. On the character sheet on the Attributes tab add "Superiority Die" to one of the 1 (Primary)Resource blocks and set the available quantity to the player's appropriate level according to the guidelines of Battle Mater Maneuvers.
	2. On each Maneuver, set the Resource consumption to Attribute/resources.primary.value/1 (Note if you used the secondary or tertiary Resource block on the attributes tab CS to set this reference accordingly.)
Superiority Die Rolls…

**Comment by jbowensii** [comment]
First sorry for the delay... life happened... 
Second... thank you, there is now a README section "DETAILED INSTRUCTIONS provided by rprejean"
Third... Happy Holidays... 
Fourth... I am updating everything for V10 and the final changes to all of the modules I use... send a discord friend invite... if that does not work open a bug here, please.

Thanks again...
