### ISSUE TITLE
Bait and Switch does not work

### ISSUE THREAD

**Issue by Zamrod** [jbowensii/More-Automated-Spells-Items-and-Feats#2]
If you activate Bait and Switch it outputs a blank chat card with only the name of the ability. I guess a dialog should appear but it does not

**Comment by Zamrod** [comment]
after some testing This only happens if you don't Gabe The superiority die affect on The character or if you don't have a token targeted

**Comment by jbowensii** [comment]
This is correct, on the front page of this github under the README there is a Battle Master Maneuver Setup section. It does have instructions for setting up and generally using all of the Battlemaster Maneuvers.  

<img width="953" alt="image" src="https://user-images.githubusercontent.com/76136571/164209517-306a93ba-3d3c-44ad-a9d7-eceb251c8279.png">

For Bait and Switch and my other scripts I will endeavor to expand upon their usage instructions, there have been several folks that have pointed out they are not specific enough.  Thank you for that feedback. 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/76136571/164211020-4ffb2e13-adeb-41a9-bf27-e27e939cdc57.png">

**Comment by jbowensii** [comment]
As for the superiority die, most of these maneuvers are NOT scripts, they use just DAE and midi.  Having a separate Superiority die is the only way I can avoid everything being a script, which is not efficient for the game would really slow down gameplay. 

I use DDB Importer from Mr. Primate and am a HUGE fan of his work.  There is a setting for any item to have the importer ignore it on updates, kinda locking it in place. 

<img width="557" alt="image" src="https://user-images.githubusercontent.com/76136571/164212324-92b406a9-8b1a-4c7f-b48b-0a941a2a5224.png">

I put all of my automation in the DDB Override compendium, along with automation(s) from Mr. Posney and Crymic... both of which do awesome work btw.  

Thanks for the feedback... John
