### ISSUE TITLE
Request: Remove requirement for Superiority Die effect

### ISSUE THREAD

**Issue by Zamrod** [jbowensii/More-Automated-Spells-Items-and-Feats#3]
When using Commanding Presence it adds an effect that adds + 0 to your rolls.

EDIT: Apparently this is due to not having the Superiority Die effect on the character. Is there a way that the scripts could each individually calculate the value rather than require this effect? I ask because I'm running public games with strangers and I'm importing their character from D&D Beyond and using the effects in an override compendium so your version of those effects are being imported instead. This fails to work since you need to manually copy the effect over to the character afterwards.

**Comment by jbowensii** [comment]
As for the superiority die, most of these maneuvers are NOT scripts, they use just DAE and midi.  Having a separate Superiority die is the only way I can avoid everything being a script, which is not efficient for the game would really slow down gameplay. 

I use DDB Importer from Mr. Primate and am a HUGE fan of his work.  There is a setting for any item to have the importer ignore it on updates, kinda locking it in place. 

<img width="557" alt="image" src="https://user-images.githubusercontent.com/76136571/164212324-92b406a9-8b1a-4c7f-b48b-0a941a2a5224.png">

I put all of my automation in the DDB Override compendium, along with automation(s) from Mr. Posney and Crymic... both of which do awesome work btw.  

Thanks for the feedback... John
