### ISSUE TITLE
Piercer Feat

### ISSUE THREAD

**Issue by delioan** [jbowensii/More-Automated-Spells-Items-and-Feats#3]
Hello ! I would like to start by thanking you for such an amazing work. The Piercer Feat seems to be broken (fvtt V10.285, dnd5e v 2.0.2).
It imports normally and adds an active ability (marked with AE index) and a passive effect (the latter with picture that points to a wrong directory).
But then, neither the critical bonus dice seems to work, nor the reroll dialogue (dialogue picture points at wrong directory, temporary effect reroll is added but never disappears, fail message about EmbeddedCollection appears at the top of the screen).
Would really love to see it in action as intended :)

**Comment by jbowensii** [comment]
Thank you, repaired and tested, will be published as soon as I finish fixing battlemaster parry.  If you like the individual file is already on github, just not my module package. please test and let me know, thank you.
