### ISSUE TITLE
Forge is mistakenly blocking this module

### ISSUE THREAD

**Issue by MotoMoto1234** [jbowensii/More-Automated-Spells-Items-and-Feats#4]
I think they are misreading your description of the module.  Maybe you have to post in their forum to see why they are blocking the compendiums from populating?  It works if one locally hosts or manually installs with the module.json url.

**Comment by jbowensii** [comment]
Sorry about the delay... life happened and I am in the middle of updating my module now that FoundryV10 and the modules I rely on are reasonably stable... and I have some time due to the holidays.  Happy Holidays BTW.  Anyway, I have sent an inquiry to THE FORGE and will let you know.

**Comment by jbowensii** [comment]
As per The Forge...
Thanks for reaching out. Your module is definitely listed on The Forge- you can find it here: https://forge-vtt.com/bazaar#search=%5B%22More%20Automated%22%5D&package=more-automated-spells-items-and-feats

Let us know if you have any other questions or concerns. We'd be happy to help. And a happy holidays to you!

Thank you,
Jim
The Forge

**Comment by MotoMoto1234** [comment]
It lists the module but none of the compendiums are populated for forge users, though I'm a third party poster for this as I do not use forge, but multiple users reported the compendiums being empty when they installed 1.1 of MASIF.  The only thing the two users could sus out that was different was their hosting method and when they installed locally everything was there.

**Comment by jbowensii** [comment]
Could you ask them to try now that I am a fully compatible V10 module... if they are empty just put in an issue on github please, The Forge seemed to be willing to help me when I spoke to them before.  I self host so I do not test on the forge. 
    On Tuesday, January 3, 2023 at 07:40:08 PM EST, MotoMoto1234 ***@***.***> wrote:  
 
 


It lists the module but none of the compendiums are populated for forge users, though I'm a third party poster for this as I do not use forge, but multiple users reported the compendiums being empty when they installed 1.1 of MASIF. The only thing the two users could sus out that was different was their hosting method and when they installed locally everything was there.

**Comment by turboraton** [comment]
Hello there, Forge user here and I can confirm that the module is being blocked by Forge and won't even let me initiate my world.

**Comment by rikmarais** [comment]
Hey there 👋 
Apologies for resurrecting a closed issue, but if you're still running into this @turboraton, make sure you update to v2.0.0 of this module and let us know in The Forge's Discord support if you are still encountering issues. 
The Forge doesn't block this module, but we've verified that `v1.1.0` packs don't load properly but `v2.0.0` does👍
